version: '3.9'

services:
  postgres:
    image: pgrouting/pgrouting:16-3.5-4.0
    container_name: flood_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-flood}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-floodpw}
      POSTGRES_DB: ${DB_NAME:-flood_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 최초 부팅시 자동 실행
      - ./backend/node/src/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U ${DB_USER:-flood}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flood_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: flood_mqtt
    restart: unless-stopped
    ports:
      - "1883:1883" #MQTT
      - "9001:9001" #WebSocket
    volumes:
      - ./infra/mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
  
  node-api:
    build:
      context: ./backend/node
      dockerfile: Dockerfile
    container_name: flood_node_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-flood}
      DB_PASSWORD: ${DB_NAME:-flood_db}
      REDIS_URL: redis://redis:6379
      MQTT_URL: mqtt://mosquitto:1883
      PYTHON_API_URL: http://python-api:8000
      JWT_SECRET: ${JWT_SECRET:-changeme}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    volumes:
      - ./backend/node:/app
      - /app/node_modules

  python-api:
    build:
      context: ./backend/python-api
      dockerfile: Dockerfile
    container_name: flood_python_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-flood}
      DB_PASSWORK: ${DB_PASSWORD:-floodpw}
      DB_NAME: ${DB_NAME:-flood_db}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/python-api:/app
      - ./backend/python-api/ml/model/artifacts:/app/ml/model/artifacts

volumes:
  postgres_data:
  redis_data:
  mosquitto_data:
  mosquitto_log: